version: '3.8'
services:
  backend:
    build: backend
    hostname: backend-host
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build: frontend
    hostname: frontend-host
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - BACKEND_URL=http://backend-host:8000
      
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network: {}